# Generated by Django 4.1.5 on 2023-01-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='song',
            field=models.ManyToManyField(related_name='songs_play_lists', to='sounds.sound'),
        ),
    ]
