# Generated by Django 4.1.5 on 2023-01-23 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
                ('avail', models.CharField(choices=[('available', 'Доступно'), ('not available', 'Не доступно')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sounds', to='category.genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
