# Generated by Django 4.1.5 on 2023-01-27 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sounds.sound'),
        ),
        migrations.AddField(
            model_name='favorites',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='favorites',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='sounds.sound'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sounds.sound'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'sound')},
        ),
        migrations.AlterUniqueTogether(
            name='favorites',
            unique_together={('owner', 'sound')},
        ),
    ]
