# Generated by Django 4.1.5 on 2023-01-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_remove_sound_avail_comment_like_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='singer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
