# Generated by Django 4.1.5 on 2023-01-25 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_sound_singer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='image',
        ),
        migrations.AddField(
            model_name='sound',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
        migrations.AddField(
            model_name='sound',
            name='file',
            field=models.FileField(blank=True, upload_to='songs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav'])]),
        ),
    ]
