# Generated by Django 4.1.5 on 2023-01-27 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sounds', '0004_remove_sound_image_sound_cover_sound_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Favorite',
        ),
        migrations.AddField(
            model_name='sound',
            name='preview',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
