# Generated by Django 4.1.5 on 2023-01-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0005_rename_favorites_favorite_sound_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='preview',
        ),
    ]
