# Generated by Django 4.1.5 on 2023-01-27 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
